/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_ENABLE_FEATURE_A 1
#define CONFIG_FEATURE_A_OPTION1 1
#define CONFIG_FEATURE_A_OPTION2 50
#define CONFIG_ENABLE_FEATURE_B 1
#define CONFIG_ADVANCED_MODE 1
#define CONFIG_ADVANCED_LEVEL 5
#define CONFIG_DEBUG_MODE 1
