/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_SECONDARY_FEATURE 1
#define CONFIG_NETWORK_ENABLED 1
#define CONFIG_NETWORK_PORT 8080
#define CONFIG_NETWORK_PROTOCOL "TCP"
#define CONFIG_NETWORK_MODE_CLIENT 1
#define CONFIG_SECURITY_ENABLED 1
#define CONFIG_SECURITY_LEVEL 5
#define CONFIG_SECURITY_ENCRYPTION 1
#define CONFIG_SECURITY_KEY_SIZE 256
