/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_SOURCED_CONFIG_BASIC 1
#define CONFIG_SOURCED_SUBMENU_CONFIG 1
#define CONFIG_SOURCED_STRING_CONFIG "source_test"
#define CONFIG_RSOURCE_OPTION_A 1
#define CONFIG_RSOURCE_INT_CONFIG 42
#define CONFIG_OSOURCED_EXISTING_CONFIG 1
#define CONFIG_OSOURCE_HEX_CONFIG 0x1000
#define CONFIG_ORSOURCE_DEPENDENT_CONFIG "orsource_value"
#define CONFIG_GLOB_FEATURE1_CONFIG 1
#define CONFIG_OPTIONAL_GLOB_CONFIG 1
#define CONFIG_NESTED_LEVEL1_CONFIG 1
#define CONFIG_NESTED_L1_MENU_CONFIG "level1"
