/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_FEATURE_A 1
#define CONFIG_FEATURE_B 1
#define CONFIG_FEATURE_C 1
#define CONFIG_FEATURE_D 1
#define CONFIG_TEST_AND_TWO 1
#define CONFIG_TEST_AND_THREE 1
#define CONFIG_TEST_AND_FOUR 1
#define CONFIG_TEST_OR_TWO 1
#define CONFIG_TEST_OR_THREE 1
#define CONFIG_TEST_OR_FOUR 1
#define CONFIG_TEST_MIXED_1 1
#define CONFIG_TEST_MIXED_2 1
#define CONFIG_TEST_MIXED_3 1
#define CONFIG_TEST_PARENS_1 1
#define CONFIG_TEST_PARENS_2 1
#define CONFIG_TEST_PARENS_3 1
#define CONFIG_TEST_PARENS_4 1
#define CONFIG_TEST_NOT_OR_1 1
#define CONFIG_TEST_NOT_OR_2 1
#define CONFIG_TEST_COMPLEX_1 1
#define CONFIG_TEST_COMPLEX_2 1
#define CONFIG_TEST_MULTI_DEPENDS 1
