/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_L1_FEATURE 1
#define CONFIG_L2_FEATURE 1
#define CONFIG_L3_FEATURE 1
#define CONFIG_L4_FEATURE 1
#define CONFIG_L4_VALUE 50
#define CONFIG_L3_ANOTHER_FEATURE 1
#define CONFIG_NETWORK_ENABLE 1
#define CONFIG_WIFI_ENABLE 1
#define CONFIG_WIFI_SSID "MyNetwork"
#define CONFIG_WIFI_AUTH_WPA2 1
#define CONFIG_WIFI_PASSWORD ""
#define CONFIG_ETHERNET_ENABLE 1
#define CONFIG_ETH_PHY_ADDR 1
#define CONFIG_MEM_POOL_SIZE 256
#define CONFIG_USE_CUSTOM_ALLOCATOR 1
#define CONFIG_ALLOCATOR_DEBUG 1
#define CONFIG_CPU_FREQ_MAX 160
#define CONFIG_TASK_WDT_TIMEOUT 5
