/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_RT_USING_DEBUG 1
#define CONFIG_RT_DEBUGING_ASSERT 1
#define CONFIG_RT_DEBUGING_COLOR 1
#define CONFIG_RT_DEBUGING_CONTEXT 1
#define CONFIG_RT_DEBUGING_AUTO_INIT 1
#define CONFIG_RT_DEBUGING_SPINLOCK 1
#define CONFIG_RT_DEBUGING_CRITICAL 1
#define CONFIG_RT_USING_SMP 1
#define CONFIG_RT_USING_SMART 1
