/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_OPTIMIZATION_LEVEL 0
#define CONFIG_THREAD_PRIORITY 100
#define CONFIG_MEMORY_SIZE 0x10000
#define CONFIG_CPU_FREQUENCY 100
#define CONFIG_FEATURE_ENABLED 1
#define CONFIG_TEST_EQ_OPT0 1
#define CONFIG_TEST_EQ_PRIORITY 1
#define CONFIG_TEST_EQ_HEX 1
#define CONFIG_TEST_LT_OPT 1
#define CONFIG_TEST_LE_OPT 1
#define CONFIG_TEST_LE_PRIORITY 1
#define CONFIG_TEST_GE_PRIORITY 1
#define CONFIG_TEST_GE_FREQ 1
#define CONFIG_TEST_COMP_OR_1 1
#define CONFIG_TEST_COMP_NOT 1
#define CONFIG_TEST_COMPLEX_NESTED 1
#define CONFIG_AUTO_ENABLE_HIGH_PERF 1
#define CONFIG_TEST_BOUNDARY_MIN 1
#define CONFIG_TEST_BOUNDARY_RANGE 1
