/*
 * Automatically generated file; DO NOT EDIT.
 */

#define CONFIG_ARCH_ARM 1
#define CONFIG_ARCH_RISCV 1
#define CONFIG_ARCH_X86 1
#define CONFIG_CPU_64BIT 1
#define CONFIG_DEBUG_MODE 1
#define CONFIG_RELEASE_MODE 1
#define CONFIG_OPTIMIZATION_LEVEL 0
#define CONFIG_ENABLE_DMA 1
#define CONFIG_ENABLE_CACHE 1
#define CONFIG_MEMORY_SIZE 0x100000
#define CONFIG_COMPLEX_DEP_1 1
#define CONFIG_COMPLEX_DEP_3 1
#define CONFIG_COMPLEX_DEP_4 1
#define CONFIG_BASE_LIB_A 1
#define CONFIG_BASE_LIB_B 1
#define CONFIG_BASE_LIB_C 1
#define CONFIG_MEMORY_POOL_SIZE 8192
#define CONFIG_ARM64_DEBUG_FEATURE 1
#define CONFIG_ARM64_DMA_DEBUG 1
#define CONFIG_ALLOCATOR_STANDARD 1
#define CONFIG_POOL_COUNT 4
#define CONFIG_EXTREME_COMPLEX_2 1
#define CONFIG_PLATFORM_EMBEDDED 1
#define CONFIG_ENABLE_NETWORKING 1
#define CONFIG_NETWORK_BUFFER_SIZE 8192
#define CONFIG_LWIP 1
#define CONFIG_LWIP_DEBUG 1
